apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcppubsubtopicencryptionv1
  annotations:
    description: >-
      Enforce encryption of PubSub Topic
spec:
  crd:
    spec:
      names:
        kind: GCPPubSubTopicEncryptionV1
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package GCPPubSubTopicEncryptionV1
        
        violation[{"msg": msg}] {
          asset := input.review.object
          asset.kind == "PubSubTopic"

          msg := checkEncryption(asset)

        }

        # check if encryption is enabled
        checkEncryption(asset) = msg {

          # find KMS key reference for the Topic
          not asset.spec.kmsKeyRef.name
          topicName := asset.metadata.name

          msg := sprintf("Encryption is not configured for Pub/Sub Topic: %v. Encryption is required.", [topicName])
        }
