apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPAllowedResourceTypesConstraintV2
filters: []
terms: {}
metadata:
  name: deny_some_resource_types
  annotations:
    description: Restricts kind of resources that are allowed in your projects.
    fr_index:
    cobit_mapping:
spec:
  severity: high
  match:
    ancestries:
    - "organizations/**"
    excludedAncestries: []
  parameters:
    mode: "denylist"
    resource_type_list:
    - sqladmin.googleapis.com/Instance
    - dataproc.googleapis.com/Job
