apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPAPIKeyRestrictionConstraintV1
metadata:
  name: gcpapikeyrestrictionconstraintv1
  annotations:
    description:  Ensure there are no API Keys that are unrestricted within your Google Cloud Organization
spec:
  severity: high
  match:
    ancestries:
    - "organizations/**"
    excludedAncestries: []
  parameters: {}