apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPCMEKSettingsConstraintV1
metadata:
  name: cmek_rotation_one_year
  annotations:
    benchmark: MAS_TRM_10.2.10
spec:
  severity: high
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters:
    # Valid time units are  "ns", "us", "ms", "s", "m", "h"
    # This is 90 days
    rotation_period: 186h
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    purpose: ENCRYPT_DECRYPT
    protection_level: SOFTWARE