apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV3
metadata:
  name: block_service_account_creator
  annotations:
    description: Ban any users from being granted Service Account Creator access
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 1.0X  # TODO: Update this with final number when the CIS benchmark is finalized
spec:
  severity: high
  match:
    target:
    - "organizations/**"
    exclude: []
  parameters:
    mode: denylist
    assetType: cloudresourcemanager.googleapis.com/Project
    role: roles/iam.serviceAccountUser
    members:
    - "*"