apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPLegacyNetworkBlockedConstraintV1
metadata:
  name: gcp-legacy-network-blocked-constraint
  annotations:
    description:  Ensure that legacy Networks are not being used within GCP Projects
spec:
  severity: high
  match:
    ancestries:
    - "projects/**"
    excludedAncestries: []
  parameters: {}
