apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPStorageLoggingItselfConstraintV1
metadata:
  name: gcp-storage-logging-itself-constrain-tv1
  annotations:
    description: Ensure buckets should not log to itself
spec:
  severity: low
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters: {}