apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeDiskResourcePoliciesConstraintV1
metadata:
  name: compute_disk_resource_policies_default
  annotations:
    benchmark: MAS_TRM_11.1.3
spec:
  severity: high
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters:
    mode: "allowlist"
    resorucePolicies:
      - https://www.googleapis.com/compute/v1/projects/devops-sandbox-20200519/zones/asia-south1-1/resourcePolicies/test-schedule