apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeRequireOSLoginConstraintV1
metadata:
  name: compute-enable-oslogin-project
  annotations:
    description: "Verifies that all VMs in a project have OS login enabled."
    benchmark: MAS_TRM_11.1.3
spec:
  severity: high
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters: {}