apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeIpForwardConstraintV2
metadata:
  name: forbid_ip_forward_default
  annotations:
    description: "Check if ip forwarding is disabled."
    benchmark: MAS_TRM_11.1.3
spec:
  severity: high
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters: {}