# policies/constraints/tf_compute_address_internal_only.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPCloudArmorRateLimitConstraintV1
metadata:
  name: gcpcloudarmorratelimitconstraintv1
spec:
  severity: high
  match:
    addresses:
    - "**"
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters:
    rate_limit_threshold: 15
