# policies/constraints/tf_compute_address_internal_only.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPCloudArmorEnableAdaptiveProtectionConstraintV1
metadata:
  name: gcpcloudarmorenableadaptiveprotectionconstraintv1
spec:
  severity: high
  match:
    address:
      - "**"
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters: {}
