# policies/constraints/tf_compute_address_internal_only.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPCloudArmorEnableVerboseLoggingConstraintV1
metadata:
  name: gcpcloudarmorenableverboseloggingconstraintv1
spec:
  severity: high
  match:
    addresses:
    - "**"
  ancestries:
    - "organizations/**"
  excludedAncestries: [ ]
  parameters:
    allowed_logging_types:
    - VERBOSE
