apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPStorageBucketWorldReadableConstraintV1
metadata:
  name: require_storage_iam
  annotations:
    name: gcp_storage_bucket_public_read_block
    benchmark: MAS_TRM_11.1.3
spec:
  severity: high
  match:
    ancestries:
      - "organizations/**"
    excludedAncestries: [ ]
  parameters: {}