apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPArtifactRegistryEncryptionV1
metadata:
  name: artifact-registry-encryption-enabled
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - artifactregistry.cnrm.cloud.google.com
      kinds:
      - ArtifactRegistryRepository
