apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPSQLEncryptionV1
metadata:
  name: cloud-sql-instance-encryption-enabled
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - sql.cnrm.cloud.google.com
      kinds:
      - SQLInstance
