version: "1.0"
landing_zone:
  type: "pbmm-gcp"

regions:
  primary: "northamerica-northeast1"
  secondary: "northamerica-northeast2"

business_units:
  - business_code: "bu1"
    business_unit: "Business Unit 1"
    location_kms: "ca"
    location_gcs: "ca"
    tfc_org_name: "example-org"
    gcs_bucket_prefix: "bkt"
    folder_prefix: "fldr"
    primary_contact: "admin@example.com"
    secondary_contact: "backup@example.com"
    development:
      env_code: "d"
      billing_code: "1234"
      env_enabled: true
      windows_activation_enabled: true
      firewall_logging_enabled: true
      optional_fw_rules_enabled: true
      vpc_flow_logs_enabled: true
      peering_iap_fw_rules_enabled: true
      key_ring_name: "dev-keyring"
      key_name: "dev-key"
      key_rotation_period: "7776000s"
      base:
        enabled: true
        ip_ranges:
          subnet1: "10.0.0.0/24"
          subnet2: "10.0.1.0/24"
        projects:
          - id: "dev-project-1"
            name: "Development Project 1"
            services:
              - "compute.googleapis.com"
              - "container.googleapis.com"
      restricted:
        enabled: false
        ip_ranges: {}
        projects: []
        vpc_scp: false

  - business_code: "bu2"
    business_unit: "Business Unit 2"
    location_kms: "ca"
    location_gcs: "ca"
    tfc_org_name: "example-org"
    gcs_bucket_prefix: "bkt"
    folder_prefix: "fldr"
    primary_contact: "admin2@example.com"
    secondary_contact: "backup2@example.com"
    production:
      env_code: "p"
      billing_code: "5678"
      env_enabled: true
      windows_activation_enabled: false
      firewall_logging_enabled: true
      optional_fw_rules_enabled: true
      vpc_flow_logs_enabled: true
      peering_iap_fw_rules_enabled: false
      key_ring_name: "prod-keyring"
      key_name: "prod-key"
      key_rotation_period: "7776000s"
      base:
        enabled: true
        ip_ranges:
          subnet1: "10.1.0.0/24"
          subnet2: "10.1.1.0/24"
        projects:
          - id: "prod-project-1"
            name: "Production Project 1"
            services:
              - "compute.googleapis.com"
              - "container.googleapis.com"
      restricted:
        enabled: true
        ip_ranges:
          subnet1: "192.168.0.0/24"
        projects:
          - id: "prod-restricted-1"
            name: "Production Restricted Project 1"
            services:
              - "compute.googleapis.com"
        vpc_scp: true

bootstrap:
  org_id: "123456789012"
  billing_account: "ABCDEF-GHIJKL-MNOPQR"
  default_region: "northamerica-northeast1"
  groups:
    create_required_groups: true
    create_optional_groups: true
    billing_project: "my-bootstrap-project"
    required_groups:
      group_org_admins: "gcp-organization-admins@example.com"
      group_billing_admins: "gcp-billing-admins@example.com"
      billing_data_users: "gcp-billing-data@example.com"
      audit_data_users: "gcp-audit-data@example.com"
      monitoring_workspace_users: "gcp-monitoring-workspace@example.com"
    optional_groups:
      gcp_security_reviewer: "gcp-security-reviewer@example.com"
      gcp_network_viewer: "gcp-network-viewer@example.com"
      gcp_scc_admin: "gcp-scc-admin@example.com"
      gcp_global_secrets_admin: "gcp-global-secrets-admin@example.com"
      gcp_kms_admin: "gcp-kms-admin@example.com"

org:
  parent_folder: "folders/12345678"
  billing_data_users: "gcp-billing-data@example.com"
  audit_data_users: "gcp-audit-data@example.com"
  scc_notification_name: "my-scc-notification"
  scc_notifications_filter: "state = \"ACTIVE\""

environments:
  - name: "development"
    environment_code: "d"
    monitoring:
      enable_monitoring: true
      monitoring_workspace_users: "gcp-monitoring-workspace@example.com"
  - name: "non-production"
    environment_code: "n"
    monitoring:
      enable_monitoring: true
      monitoring_workspace_users: "gcp-monitoring-workspace@example.com"
  - name: "production"
    environment_code: "p"
    monitoring:
      enable_monitoring: true
      monitoring_workspace_users: "gcp-monitoring-workspace@example.com"

networking:
  enable_hub_and_spoke: true
  enable_vpn: true
  dns_enable_logging: true
  shared_vpc_host_project_id: "shared-vpc-host"
  base_network:
    network_name: "base-network"
    subnets:
      - subnet_name: "subnet-01"
        subnet_ip: "10.0.0.0/24"
        subnet_region: "northamerica-northeast1"
      - subnet_name: "subnet-02"
        subnet_ip: "10.0.1.0/24"
        subnet_region: "northamerica-northeast1"

projects:
  common:
    billing_account: "ABCDEF-GHIJKL-MNOPQR"
    parent_folder: "folders/12345678"
    vpc_type: "base"
    alert_spent_percents: [0.5, 0.75, 0.9, 0.95]
    alert_pubsub_topic: "billing-alerts"
    budget_amount: 1000
  environments:
    - environment: "development"
      projects:
        - name: "sample-app-dev"
          apis: 
            - "compute.googleapis.com"
            - "container.googleapis.com"
          labels:
            environment: "development"
            application: "sample-app"
    - environment: "production"
      projects:
        - name: "sample-app-prod"
          apis:
            - "compute.googleapis.com"
            - "container.googleapis.com"
          labels:
            environment: "production"
            application: "sample-app"

app_infra:
  environments:
    - environment: "development"
      business_units:
        - name: "bu1"
          gke_clusters:
            - name: "gke-dev-1"
              region: "northamerica-northeast1"
              network_config:
                network: "dev-network"
                subnetwork: "dev-subnet"
                ip_range_pods: "10.10.0.0/16"
                ip_range_services: "10.20.0.0/16"
    - environment: "production"
      business_units:
        - name: "bu1"
          gke_clusters:
            - name: "gke-prod-1"
              region: "northamerica-northeast1"
              network_config:
                network: "prod-network"
                subnetwork: "prod-subnet"
                ip_range_pods: "10.30.0.0/16"
                ip_range_services: "10.40.0.0/16"

org_policies:
  policy_boolean:
    vmExternalIpAccess: false
    skipDefaultNetworkCreation: true
    disableSerialPortAccess: true
    disableDefaultIamGrantsServiceAccounts: true
  policy_list:
    restrictVpcPeering:
      - "under:folders/12345678"
    restrictSharedVpcSubnetworks:
      - "projects/host-project"
    restrictSharedVpcHostProjects:
      - "projects/host-project"

fortigate:
  enabled: true
  version: "7.2.3"
  license_type: "byol"
  config:
    ha_enabled: true
    regions:
      - "northamerica-northeast1"
    machine_type: "n2-standard-4"
    service_account: "fortigate-sa@project-id.iam.gserviceaccount.com"
    networks:
      - name: "external"
        cidr: "192.168.1.0/24"
      - name: "internal"
        cidr: "192.168.2.0/24"
      - name: "hasync"
        cidr: "192.168.3.0/24"
      - name: "mgmt"
        cidr: "192.168.4.0/24"
