steps:
  # Clone the repository
  - name: gcr.io/cloud-builders/git
    args: ['clone', '--branch', 'main', 'https://github.com/gurneesh-kubeshot/pbmm-gcp-test.git']
    id: 'check-out-source'

  # Get the service account key from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    id: 'get-sa-key'
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SECRET" > /workspace/sa-key.json
    secretEnv: ['SECRET']

  # Install dependencies and run deployment
  - id: 'deploy'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - -c
    - |
      cd pbmm-gcp-test
      
      # Install system dependencies
      apt-get update && apt-get install -y \
        wget \
        unzip \
        python3 \
        python3-pip \
        dos2unix \
        jq \
        google-cloud-sdk \
        google-cloud-cli-terraform-tools
      
      # Install Terraform
      wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      unzip terraform_1.6.0_linux_amd64.zip
      mv terraform /usr/local/bin/
      chmod +x /usr/local/bin/terraform
      
      # Install Python dependencies
      pip3 install pyyaml google-cloud-devtools-cloudbuild rich jsonschema
      
      # Set file permissions
      find . -type f -name "*.sh" | xargs chmod a+x
      find . -type f -name "*.sh" | xargs dos2unix
      
      # Set environment variables
      export REGION=${_REGION}
      export ORG_ID=${_ORG_ID}
      export ROOT_FOLDER_ID=${_ROOT_FOLDER_ID}
      export BILLING_ID=${_BILLING_ID}
      
      echo "Environment variables set:"
      echo "REGION: ${_REGION}"
      echo "ORG_ID: ${_ORG_ID}"
      echo "ROOT_FOLDER_ID: ${_ROOT_FOLDER_ID}"
      echo "BILLING_ID: ${_BILLING_ID}"
      
      # Run deployment script
      cd landing-zones/gcp-landing-zone
      chmod +x automation-scripts/deploy.sh
      ./automation-scripts/deploy.sh \
        -k /workspace/sa-key.json \
        -p ${_PROJECT_ID} \
        -m plan

logsBucket: 'gs://build-logs-${_PROJECT_ID}/cloudbuild-logs'

availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/${_SA_KEY_SECRET}/versions/latest
    env: 'SECRET'

substitutions:
  _PROJECT_ID: '' # Project ID where secrets are stored
  _SA_KEY_SECRET: 'terraform-sa-key' # Name of the secret containing the service account key
  _REGION: ''
  _ORG_ID: ''
  _ROOT_FOLDER_ID: ''
  _BILLING_ID: '' 