apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPPubSubTopicEncryptionV1
metadata:
  name: pubsub-topic-encryption-enabled
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - pubsub.cnrm.cloud.google.com
      kinds:
      - PubSubTopic
